"""Packs Noita's spell icons into mods/wands/icons.ts.

Input: the Noita wiki's "Spells" page saved as a complete HTML file (it embeds every spell icon as a WebP data URL
in a CSS variable, and names it in the <img alt> of the spell's tile). Output: icons.ts with one shared palette and,
per spell name, the 16x16 icon run-length coded against it, decoded by art.ts at start-up (synchronously, so icons
can be painted onto cards and used as textures).

    python3 mods/wands/tools/make_icons.py ~/Downloads/Spells.html

Needs Pillow. The icons are Nolla Games' artwork, taken from the wiki.
"""
import base64, html, io, json, re, struct, sys
from pathlib import Path
from PIL import Image

src = Path(sys.argv[1]).read_text(encoding='utf-8')
out = Path(__file__).resolve().parent.parent / 'icons.ts'

webp = dict(re.findall(r'--sf-img-(\d+):\s*url\(["\']?data:image/webp;base64,([A-Za-z0-9+/=]+)', src))
names = {}
for m in re.finditer(r'''<div class="SQI-row spellBorder spellBackground w2tiptarget spell\w+[^>]*><a href=[^ >]+ title=(?:"([^"]+)"|([^ >]+))><img alt=(?:"[^"]*"|[^ ]+) src='[^']*'[^>]*?var\(--sf-img-(\d+)\)''', src):
    name = html.unescape(m.group(1) or m.group(2))
    names.setdefault(name, m.group(3))

palette, index = [], {}
icons = {}
for name, img in sorted(names.items()):
    im = Image.open(io.BytesIO(base64.b64decode(webp[img]))).convert('RGBA')
    # the wiki shows them at 5x: back to 16x16, one source pixel per block (the block's centre)
    im = im.resize((16, 16), Image.NEAREST)
    px = list(im.getdata())
    tokens, run = [], 0
    for p in px:
        if p[3] == 0:
            run += 1
            continue
        if run: tokens.append(0x8000 | run); run = 0
        if p not in index: index[p] = len(palette); palette.append(p)
        tokens.append(index[p])
    if run: tokens.append(0x8000 | run)
    icons[name] = base64.b64encode(struct.pack(f'<{len(tokens)}H', *tokens)).decode()

pal = base64.b64encode(bytes(c for p in palette for c in p)).decode()
lines = [
    '// Generated by tools/make_icons.py from the Noita wiki: do not edit. Noita spell icons (Nolla Games\' artwork),',
    '// 16x16, keyed by the spell\'s English name. PALETTE is RGBA bytes; each icon is little-endian 16-bit tokens:',
    '// a palette index, or 0x8000 | n for n transparent pixels. art.ts decodes them.',
    f'export const PALETTE = {json.dumps(pal)};',
    'export const ICONS: Record<string, string> = {',
]
lines += [f'  {json.dumps(k)}: {json.dumps(v)},' for k, v in icons.items()]
lines.append('};')
out.write_text('\n'.join(lines) + '\n')
print(f'{len(icons)} icons, {len(palette)} colours, {out.stat().st_size} bytes -> {out}')
