"""Packs Noita's spell icons into mods/wands/icons.ts.

Input: the Noita wiki's "Spells" page saved as a complete HTML file (it embeds every spell icon as a WebP data URL
in a CSS variable, and names it in the <img alt> of the spell's tile). Output: icons.ts, decoded by iconcodec.ts.

    python3 mods/wands/tools/make_icons.py ~/Downloads/Spells.html

The format (lossless, about a third of plain RGBA run-length coding): one RGBA palette shared by all icons, then
one bit stream (least significant bit first) holding, per icon in NAMES order:

    6 bits   n: colours this icon uses
    n x 11   their indices in the shared palette
    4 x 4    the box around its visible pixels: x0, y0, x1, y1
    per pixel in the box, row by row: 1 bit visible; if visible and n > 1, ceil(log2 n) bits: which of its colours

Needs Pillow. The icons are Nolla Games' artwork, taken from the wiki.
"""
import base64, html, io, json, re, sys
from pathlib import Path
from PIL import Image

src = Path(sys.argv[1]).read_text(encoding='utf-8')
out = Path(__file__).resolve().parent.parent / 'icons.ts'

webp = dict(re.findall(r'--sf-img-(\d+):\s*url\(["\']?data:image/webp;base64,([A-Za-z0-9+/=]+)', src))
names = {}
for m in re.finditer(r'''<div class="SQI-row spellBorder spellBackground w2tiptarget spell\w+[^>]*><a href=[^ >]+ title=(?:"([^"]+)"|([^ >]+))><img alt=(?:"[^"]*"|[^ ]+) src='[^']*'[^>]*?var\(--sf-img-(\d+)\)''', src):
    name = html.unescape(m.group(1) or m.group(2))
    names.setdefault(name, m.group(3))


class Bits:
    def __init__(self): self.out, self.acc, self.n = bytearray(), 0, 0
    def put(self, v, bits):
        self.acc |= v << self.n
        self.n += bits
        while self.n >= 8:
            self.out.append(self.acc & 255); self.acc >>= 8; self.n -= 8
    def bytes(self):
        return bytes(self.out) + (bytes([self.acc & 255]) if self.n else b'')


palette, index = [], {}
bits = Bits()
order = sorted(names)
for name in order:
    im = Image.open(io.BytesIO(base64.b64decode(webp[names[name]]))).convert('RGBA')
    # the wiki shows them at 5x: back to 16x16, one source pixel per block (the block's centre)
    px = list(im.resize((16, 16), Image.NEAREST).getdata())
    for p in px:
        if p[3] and p not in index: index[p] = len(palette); palette.append(p)
    local = sorted({index[p] for p in px if p[3]})
    assert len(local) < 64 and len(palette) < 2048
    which = {c: i for i, c in enumerate(local)}
    cbits = (len(local) - 1).bit_length()
    bits.put(len(local), 6)
    for c in local: bits.put(c, 11)
    vis = [i for i, p in enumerate(px) if p[3]] or [0]
    x0, x1 = min(i % 16 for i in vis), max(i % 16 for i in vis)
    y0, y1 = min(i // 16 for i in vis), max(i // 16 for i in vis)
    for v in (x0, y0, x1, y1): bits.put(v, 4)
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            p = px[y * 16 + x]
            bits.put(1 if p[3] else 0, 1)
            if p[3] and cbits: bits.put(which[index[p]], cbits)

pal = base64.b64encode(bytes(c for p in palette for c in p)).decode()
data = base64.b64encode(bits.bytes()).decode()
lines = [
    '// Generated by tools/make_icons.py from the Noita wiki: do not edit. Noita spell icons (Nolla Games\' artwork), 16x16,',
    '// in NAMES order (the spells\' English names); iconcodec.ts decodes them. The format is described in make_icons.py.',
    f'export const NAMES: string[] = {json.dumps(order, ensure_ascii=False)};',
    f'export const PALETTE = {json.dumps(pal)};',
    f'export const DATA = {json.dumps(data)};',
]
out.write_text('\n'.join(lines) + '\n')
print(f'{len(order)} icons, {len(palette)} colours, {out.stat().st_size} bytes -> {out}')
